experiment_name: protocbm_independent_tuning
base_config: configs/protocbm/independent.yaml
num_trials: 50

optimize:
  loss_weight_attribute_decorrelation:
    distribution: loguniform
    low: 1e-5
    high: 1e2
  loss_weight_map_compactness:
    distribution: loguniform
    low: 1e-5
    high: 1e2
  lr:
    distribution: categorical
    values: [0.01, 0.005, 0.001, 0.0005, 0.0001]