experiment_name: protocbm_x-to-c_tuning
base_config: configs/protocbm/modes/independent.yaml
num_trials: 50
val_metric:
  - dist_loc

mode: XC
epochs: 150

optimize:
  loss_weight_attribute_decorrelation:
    distribution: categorical
    values: [0.1, 0.01, 0.001]
  loss_weight_map_compactness:
    distribution: categorical
    values: [0.1, 0.01, 0.001]
  lr:
    distribution: categorical
    values: [0.01, 0.001]