experiment_name: protocbm_joint_tuning
base_config: configs/protocbm/modes/joint.yaml
num_trials: 150
epochs: 100
val_metric:
  - concept_acc
  - class_acc
  - dist_loc

optimize:
  # Also tune attribute regression weight to control it compared to classification loss.
  loss_weight_attribute_reg:
    distribution: loguniform
    low: 0.1
    high: 10
  loss_weight_attribute_decorrelation:
    distribution: loguniform
    low: 0.0001
    high: 1
  loss_weight_map_compactness:
    distribution: loguniform
    low: 0.0001
    high: 1
  lr:
    distribution: categorical
    values: [0.01]