base_config: configs/protocbm/protocbm.yaml
mode: C*Y
log_dir: outputs/protocbm/independent_classifier
checkpoint: seq_xc.pth

use_aux: false
val_metric: class_acc

# --- TO BE UPDATED ---
lr: 0.01

loss_weight_attribute_reg: 0.8886
loss_weight_map_compactness: 0.01
loss_weight_attribute_decorrelation: 0.008823125255077393
