base_config: configs/protocbm/protocbm.yaml
mode: XCY
log_dir: outputs/protocbm/main/joint_1

# --- TO BE UPDATED ---
lr: 0.01

val_metric:   # Options: [class_acc, concept_acc, seg_iou, dist_loc], multiple can be combined.
  - class_acc
  - concept_acc

loss_weight_attribute_reg: 7.8
loss_weight_map_compactness: 0.001
loss_weight_attribute_decorrelation: 0.001