base_config: configs/protocbm/protocbm.yaml
mode: XC
log_dir: outputs/protocbm/xc

# --- TO BE UPDATED ---
lr: 0.01

loss_weight_attribute_reg: 1
loss_weight_map_compactness: 0.000035
loss_weight_attribute_decorrelation: 0.00012