mode: XCY   # XY and XC and CY
n_attributes: 112

model_name: protocbm
concept_mapper: protomod
concept_activation: none    # "relu" or "sigmoid"

salieny_method: attention
IoU_threshold: 0.5

log_dir: outputs/ProtoCBM
data_dir: data/CUB_200_2011
split_dir: data/CUB_processed/class_attr_data_10
part_seg_dir: 
vis_every_n: 15
seed: 1

batch_size: 16
use_aux: false

backbone: inception
backbone_pretrained: true
backbone_freeze: true
expand_dim: 0

proto_n_vectors: 1
