mode: XCY   # XY and XC and CY
n_attributes: 312

model_name: apn
concept_mapper: protomod
concept_activation: none    # "relu" or "sigmoid"

saliency_method: attention
IoU_threshold: 0.5
plot_curve: False

log_dir: outputs/APN
data_dir: data/CUB_200_2011
split_dir: data/CUB_processed/class_attr_data_10/test.pkl
backbone_dir: outputs/APN/resnet101_c.pth.tar
apn_weights_dir: outputs/APN/CUB_ZSL_id_0.pth
vis_every_n: 1
seed: 1

batch_size: 64
