mode: XCY   # XY and XC and CY
n_attributes: 112

model_name: protocbm
concept_mapper: protomod
concept_activation: none    # "relu" or "sigmoid"

saliency_method: attention
IoU_threshold: 0.5

log_dir: outputs/ProtoCBM_IntegrateIoU2
image_dir: data/CUB_200_2011/images
data_dir: data/CUB_processed/class_attr_data_10
checkpoint: ""
seed: 1

epochs: 1000
batch_size: 64
lr: 0.01
optimizer: sgd
scheduler_step: 1000
weight_decay: 0.00004
use_aux: true

backbone: inception
backbone_pretrained: true
backbone_freeze: false
expand_dim: 0

# ProtoCBM specifics
proto_n_vectors: 4
loss_weight_attribute_reg: 0.8886
loss_weight_map_compactness: 0.01
loss_weight_attribute_decorrelation: 0.008823125255077393
loss_decorrelation_per_group: true
