mode: XCCY   # XY, XC, XCCY and CY
n_attributes: 112

model_name: protocbm
concept_mapper: protomod
concept_activation: none    # "relu" or "sigmoid"

saliency_method: attention
IoU_threshold: 0.5
val_metric:   # Options: [class_acc, concept_acc, seg_iou, dist_loc], multiple can be combined.
  - concept_acc
  - class_acc


log_dir: outputs/XCCY
image_dir: data/CUB_200_2011
data_dir: data/CUB_processed/class_attr_data_10
checkpoint: ""
seed: 1

epochs: 1000
batch_size: 64
lr: 0.01
optimizer: sgd
scheduler_step: 1000
weight_decay: 0.00004
use_aux: true
dataset: cub

backbone: inception
backbone_pretrained: true
backbone_freeze: false
expand_dim: 0

# ProtoCBM specifics
proto_n_vectors: 1
loss_weight_attribute_reg: 0.8886
loss_weight_map_compactness: 0.01
loss_weight_attribute_decorrelation: 0.008823125255077393
loss_decorrelation_per_group: true
